# Generated by Django 3.2.9 on 2021-11-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SentMessageData',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=256)),
                ('to_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
